### ISSUE TITLE
Navbar items not fitting

### ISSUE THREAD

**Issue by esadek** [EQ-Alpha/KeyDB-docs#9]
Navbar items do not fit when the view width is 997px to 1302px.

![Screen Shot 2021-04-29 at 17 42 44](https://user-images.githubusercontent.com/8847625/116489560-1f3bef80-a84a-11eb-9e16-6bedb8afceb7.png)
![Screen Shot 2021-04-29 at 17 45 00](https://user-images.githubusercontent.com/8847625/116489562-1fd48600-a84a-11eb-94e6-a4f90574fdc1.png)

**Comment by benschermel** [comment]
Thanks, we will keep this issue open until resolved. This is also an issue in brought up previously in docusaurus https://github.com/facebook/docusaurus/issues/3820. This happened when we migrated to v2. We may do a workaround in the meantime, but until resolved we will keep it open.

**Comment by lex111** [comment]
@benschermel in later versions of Docusaurus, we made it possible to truncate a site name in navbar. As you can see, [this](https://github.com/facebookincubator/infima/pull/107) partly helps to fix the display of nav items. Please don't forget to update Docusaurus version on your site.

**Comment by benschermel** [comment]
@lex111, this is great!! I have updated docusaurus and our website. You can see the changes live now and it looks way better.

Thanks a lot!
